services:
  db:
    container_name: telco_db
    image: postgres:latest
    environment:
      POSTGRES_DB: telco_db
      POSTGRES_USER: ${DBT_USER}
      POSTGRES_PASSWORD: ${DBT_PASSWORD}
    volumes:
      - postgresql_bin:/usr/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      - telco_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DBT_USER} -d telco_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgresql_data:
    driver: local
  postgresql_bin:
    driver: local

networks:
  db: